# Generated by Django 2.0.1 on 2018-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestudiante',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
